export const TIMEOUT_MAX_VALUE = 2147483647;
export const REDIS_CACHE_NAME = 'fileStorageCache';
export const REDIS_TEMPORARY_NAME = 'fileStorageTemporary';
export const CACHE_FILES_DEFAULT_TTL = 86400; // 1 day
export const TEMPORARY_FILES_DEFAULT_TTL = 86400; // 1 day
export const DEFAULT_STATIC_PREFIX = '/static';
export const STATIC_DELIMITER = 's';
export const CACHE_DELIMITER = 'c';
export const TEMPORARY_DELIMITER = 't';
export const LOG_FILENAME_FILES_STORAGE = 'file-storage-%DATE%.log';
export const IMAGE_TRANSFORM_MAX_WITH = 3000;
export const IMAGE_TRANSFORM_MAX_HEIGHT = 3000;
export const IMAGE_TRANSFORM_MAX_BLUR = 20;
export const IMAGE_TRANSFORM_MAX_GAUSSIAN = 20;
export const DEFAULT_MAX_FIELD_SIZE = 1000000 * 64; // 64MB
export const DEFAULT_MAX_FILE_SIZE = Infinity;
export const DEFAULT_MAX_FILES = Infinity;